//! Legacy layer parameter paths remain aliases of their canonical owners.

macro_rules! assert_same_type {
    ($canonical:path, $legacy:path) => {{
        fn coerce(value: $canonical) -> $legacy {
            value
        }
        let _ = coerce as fn($canonical) -> $legacy;
    }};
}

#[test]
fn legacy_layer_parameter_paths_name_the_canonical_types() {
    assert_same_type!(terra_core::mask_types::MaskId, terra_core::mask::MaskId);
    assert_same_type!(terra_core::mask_types::MaskRef, terra_core::mask::MaskRef);
    assert_same_type!(
        terra_core::mask_types::MaskSource,
        terra_core::mask::MaskSource
    );
    assert_same_type!(
        terra_core::mask_field::MaskField,
        terra_core::mask::MaskField
    );
    assert_same_type!(terra_core::mask_ir::MaskAsset, terra_core::mask::MaskAsset);
    assert_same_type!(terra_core::mask_ir::MaskOp, terra_core::mask::MaskOp);
    assert_same_type!(
        terra_core::mask_ir::PaintBuffer,
        terra_core::mask::PaintBuffer
    );
    assert_same_type!(terra_core::mask_ir::DistNode, terra_core::mask::DistNode);
    assert_same_type!(
        terra_core::mask_ir::Distribution,
        terra_core::mask::Distribution
    );
    assert_same_type!(
        terra_core::mask_ir::PlacementDefinition,
        terra_core::mask::PlacementDefinition
    );
    assert_same_type!(
        terra_core::mask_ir::PlacementCombineMode,
        terra_core::biome_definition::PlacementCombineMode
    );
    assert_same_type!(terra_core::field_data::FieldId, terra_core::fields::FieldId);
    assert_same_type!(terra_core::field_data::AuxMaps, terra_core::fields::AuxMaps);
    assert_same_type!(
        terra_core::geology::BedGeometry,
        terra_core::material_schema::BedGeometry
    );
    assert_same_type!(
        terra_core::geology::Stratum,
        terra_core::material_schema::Stratum
    );
    assert_same_type!(
        terra_core::geology::StratumMaterial,
        terra_core::material_schema::StratumMaterial
    );
    assert_same_type!(
        terra_core::invalidation::DirtyClass,
        terra_core::tiling::DirtyClass
    );
    assert_same_type!(
        terra_core::layer::ApplyWhere,
        terra_core::operation_placement::ApplyWhere
    );
    assert_same_type!(
        terra_core::layer::OperationPlacement,
        terra_core::operation_placement::OperationPlacement
    );
    assert_same_type!(
        terra_core::layer::DevelopCategory,
        terra_core::operation_placement::DevelopCategory
    );

    assert_same_type!(
        terra_core::noise::NoiseParams,
        terra_core::layer::NoiseParams
    );
    assert_same_type!(
        terra_core::noise::WorleyParams,
        terra_core::layer::WorleyParams
    );
    assert_same_type!(
        terra_core::noise::WorleyMetric,
        terra_core::layer::WorleyMetric
    );
    assert_same_type!(
        terra_core::noise::WorleyFeature,
        terra_core::layer::WorleyFeature
    );
    assert_same_type!(
        terra_core::noise::FractalNoiseType,
        terra_core::layer::FractalNoiseType
    );

    assert_same_type!(
        terra_core::analyze::TransportModel,
        terra_core::layer::TransportModel
    );
    assert_same_type!(
        terra_core::analyze::ThermalErosionParams,
        terra_core::layer::ThermalErosionParams
    );
    assert_same_type!(
        terra_core::analyze::DebrisFlowParams,
        terra_core::layer::DebrisFlowParams
    );
    assert_same_type!(
        terra_core::analyze::HydraulicErosionParams,
        terra_core::layer::HydraulicErosionParams
    );
    assert_same_type!(
        terra_core::analyze::MultiScaleAmplifyParams,
        terra_core::layer::MultiScaleAmplifyParams
    );
    assert_same_type!(
        terra_core::hydro::StreamPowerParams,
        terra_core::layer::StreamPowerParams
    );
    assert_same_type!(
        terra_core::hydro::RiverCarveParams,
        terra_core::layer::RiverCarveParams
    );

    assert_same_type!(
        terra_core::generators::BlurParams,
        terra_core::layer::BlurParams
    );
    assert_same_type!(
        terra_core::generators::EffectFilterKind,
        terra_core::layer::EffectFilterKind
    );
    assert_same_type!(
        terra_core::generators::EffectFilterParams,
        terra_core::layer::EffectFilterParams
    );
    assert_same_type!(
        terra_core::generators::SculptParams,
        terra_core::layer::SculptParams
    );
    assert_same_type!(
        terra_core::generators::FlatParams,
        terra_core::layer::FlatParams
    );
    assert_same_type!(
        terra_core::generators::RampParams,
        terra_core::layer::RampParams
    );
    assert_same_type!(
        terra_core::generators::FbmParams,
        terra_core::layer::FbmParams
    );
    assert_same_type!(
        terra_core::generators::DomainWarpParams,
        terra_core::layer::DomainWarpParams
    );
    assert_same_type!(
        terra_core::generators::TerraceParams,
        terra_core::layer::TerraceParams
    );
    assert_same_type!(
        terra_core::generators::PlateauParams,
        terra_core::layer::PlateauParams
    );
    assert_same_type!(
        terra_core::generators::MesaParams,
        terra_core::layer::MesaParams
    );
    assert_same_type!(
        terra_core::generators::IslandArchetype,
        terra_core::layer::IslandArchetype
    );
    assert_same_type!(
        terra_core::generators::IslandParams,
        terra_core::layer::IslandParams
    );
    assert_same_type!(
        terra_core::generators::MountainParams,
        terra_core::layer::MountainParams
    );
    assert_same_type!(
        terra_core::generators::VolcanoParams,
        terra_core::layer::VolcanoParams
    );
    assert_same_type!(
        terra_core::generators::UpliftParams,
        terra_core::layer::UpliftParams
    );
    assert_same_type!(
        terra_core::generators::DuneParams,
        terra_core::layer::DuneParams
    );
    assert_same_type!(
        terra_core::generators::CanyonParams,
        terra_core::layer::CanyonParams
    );
    assert_same_type!(
        terra_core::generators::VoronoiParams,
        terra_core::layer::VoronoiParams
    );
    assert_same_type!(
        terra_core::generators::ImportHeightmapParams,
        terra_core::layer::ImportHeightmapParams
    );
    assert_same_type!(
        terra_core::generators::CoastalParams,
        terra_core::layer::CoastalParams
    );
    assert_same_type!(
        terra_core::generators::RiverNode,
        terra_core::layer::RiverNode
    );
    assert_same_type!(
        terra_core::generators::RiverNetworkParams,
        terra_core::layer::RiverNetworkParams
    );
    assert_same_type!(
        terra_core::generators::SandSimParams,
        terra_core::layer::SandSimParams
    );
    assert_same_type!(
        terra_core::generators::FluidSimParams,
        terra_core::layer::FluidSimParams
    );
    assert_same_type!(
        terra_core::generators::PathNode,
        terra_core::layer::PathNode
    );
    assert_same_type!(
        terra_core::generators::PathParams,
        terra_core::layer::PathParams
    );
    assert_same_type!(
        terra_core::generators::ProceduralGenerator,
        terra_core::layer::ProceduralGenerator
    );
    assert_same_type!(
        terra_core::generators::ProceduralShapeParams,
        terra_core::layer::ProceduralShapeParams
    );
    assert_same_type!(
        terra_core::generators::Stamp2dParams,
        terra_core::layer::Stamp2dParams
    );
    assert_same_type!(
        terra_core::generators::Stamp3dParams,
        terra_core::layer::Stamp3dParams
    );
    assert_same_type!(
        terra_core::generators::PolygonHeightMode,
        terra_core::layer::PolygonHeightMode
    );
    assert_same_type!(
        terra_core::generators::PolygonHeightParams,
        terra_core::layer::PolygonHeightParams
    );

    assert_same_type!(
        terra_core::material_schema::StratumMaterial,
        terra_core::layer::StratumMaterial
    );
    assert_same_type!(
        terra_core::material_schema::BedGeometry,
        terra_core::layer::BedGeometry
    );
    assert_same_type!(
        terra_core::material_schema::Stratum,
        terra_core::layer::Stratum
    );
    assert_same_type!(
        terra_core::material_schema::MaterialsParams,
        terra_core::layer::MaterialsParams
    );
    assert_same_type!(
        terra_core::material_schema::MaterialRule,
        terra_core::layer::MaterialRule
    );
    assert_same_type!(
        terra_core::material_schema::ClimateParams,
        terra_core::layer::ClimateParams
    );
    assert_same_type!(
        terra_core::material_schema::BiomesParams,
        terra_core::layer::BiomesParams
    );
    assert_same_type!(
        terra_core::material_schema::BiomeBand,
        terra_core::layer::BiomeBand
    );
    assert_same_type!(
        terra_core::scatter::VegetationParams,
        terra_core::layer::VegetationParams
    );
    assert_same_type!(
        terra_core::volumetric::OverhangStampParams,
        terra_core::layer::OverhangStampParams
    );
    assert_same_type!(
        terra_core::volumetric::LocalSdfParams,
        terra_core::layer::LocalSdfParams
    );
}
